version: "3.8"
services:
  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@//192.168.56.101:1521/freepdb1
      - SPRING_DATASOURCE_USERNAME=hr
      - SPRING_DATASOURCE_PASSWORD=oracle